services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mocsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - backend_node_modules:/app/node_modules
      - ./backend:/app
    working_dir: /app
    command: sh -c "npx prisma migrate dev --name init && yarn dev"
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: yarn dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  pgdata:
  backend_node_modules:
  frontend_node_modules:
