version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: mocs-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mocsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: mocs-backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app
    working_dir: /app
    command: yarn dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: mocs-frontend
    restart: always
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
